# .circleci/config.yml  (CircleCI 2.1)
version: 2.1

executors:
  docker-dind:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: false
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build_and_push:
    executor: docker-dind
    environment:
      # model and path args for your build
      MODEL_NAME: "LoneStriker/NeuralBeagle14-7B-8.0bpw-h8-exl2"
      BASE_PATH: "/models"
    steps:
      - checkout

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PAT" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: Build & push without cache
          command: |
            TAG="${CIRCLE_TAG:-latest}"
            IMG="docker.io/$DOCKERHUB_USER/vllm-discord-bot"

            docker build \
              --progress=plain \
              --no-cache \
              -t "${IMG}:${TAG}" \
              --build-arg MODEL_NAME="${MODEL_NAME}" \
              --build-arg BASE_PATH="${BASE_PATH}" \
              .

            docker push "${IMG}:${TAG}"

workflows:
  version: 2
  build_on_tag:
    jobs:
      - build_and_push:
          context: docker-hub
          filters:
            tags:
              only: /^v.*$/
            branches:
              ignore: /.*/